ALTER TABLE "PlayerGameTime"
ADD COLUMN "assists" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "PlayerGameTime"
ADD COLUMN "blocks" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "PlayerGameTime"
ADD COLUMN "rebounds" INTEGER NOT NULL DEFAULT 0;
