ALTER TABLE "Game" ADD COLUMN "currentPeriodNumber" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Game" ADD COLUMN "currentPeriodStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "Game" ADD COLUMN "periodElapsedSeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN "lastPeriodStartedAt" DATETIME;

ALTER TABLE "PlayerGameTime" ADD COLUMN "periodSeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerGameTime" ADD COLUMN "lastPeriodEnteredAt" DATETIME;
