ALTER TABLE "Team"
ADD COLUMN "userId" INTEGER;

CREATE INDEX "Team_userId_idx" ON "Team"("userId");

ALTER TABLE "Team"
ADD CONSTRAINT "Team_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
